### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by erezposner** [wenbin-lin/OcclusionFusion#2]
Great work. Are you planning on making the source code available?
Thank you

**Comment by wenbin-lin** [comment]
Thank you for your interest. We plan to make the code of the full motion estimation network public in a week or two. However, the code for the RGBD-based volumetric reconstruction system is difficult to clean up properly, so we do not plan to make it public for now.

**Comment by erezposner** [comment]
Great thank you.

**Comment by AlaaSenjab** [comment]
Thank you for your work, this is great!
Any update on making this public?

**Comment by ray8828** [comment]
+1

**Comment by hmermerkaya** [comment]
+1
